version: '2'

services:
  master:
    image: ranjandas/docker-hadoop-1.0.4 
    container_name: master.example.com
    hostname: master
    domainname: example.com
    privileged: true
    ports:
      - 50030:50030
      - 50070:50070
      - 50090:50090
      - 9000:9000
      - 9001:9001
    environment:
      - ROLE=master
    volumes:
      - ./files/etc/hadoop:/etc/hadoop:Z

  agent:
    image: ranjandas/docker-hadoop-1.0.4
    domainname: example.com
    privileged: true
    ports:
      - 50020
      - 50060
      - 50010
      - 50075
    environment:
      - ROLE=slave
    volumes:
      - ./files/etc/hadoop:/etc/hadoop:Z
